name: Fetch Data

on:
  push:
    branches:
      - main

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure the bot has write permissions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update data.json
        run: |
          echo '{"key": "value"}' > data.json
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add data.json
          git commit -m "Update data.json"
          git push
