name: Fetch Data

on:
  schedule:
    - cron: '0 * * * *' # Ejecutar cada hora
  push:
    branches:
      - main

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch data from external site
      run: |
        curl -o data.html https://www.comprasestatales.gub.uy/consultas/
        if ! git diff --exit-code data.html; then
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.html
          git commit -m 'Update data.html'
          git push
        else
          echo "No changes detected in data.html"
        fi
