name: List Recent Workflow Runs

on:
  workflow_dispatch:

jobs:
  list-workflow-runs:
    runs-on: ubuntu-latest

    steps:
    - name: List workflow runs
      id: list-runs
      uses: actions/github-script@v4
      with:
        script: |
          const runs = await github.actions.listWorkflowRunsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 10,
          });
          return runs.data.workflow_runs.map(run => run.html_url);
      
    - name: Output workflow run URLs
      run: echo "${{ steps.list-runs.outputs.results }}"
